/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package model;

import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class TarefaForm extends javax.swing.JFrame {

    /**
     * Creates new form TarefaForm
     */
    public TarefaForm() {
        initComponents();
         bnt_mostrarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_tarefa = new javax.swing.JTextField();
        jL_descricao = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        jL_prioridade = new javax.swing.JLabel();
        cbx_nivel_prioridade = new javax.swing.JComboBox<>();
        bnt_salvar = new javax.swing.JButton();
        bnt_excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bnt_mostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jL_titulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jL_titulo.setText("Gerenciador de Tarefas");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Titulo da Tarefa:");

        txt_tarefa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jL_descricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jL_descricao.setText("Descrição:");

        txt_descricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jL_prioridade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jL_prioridade.setText("Prioridade:");

        cbx_nivel_prioridade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbx_nivel_prioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta" }));

        bnt_salvar.setBackground(new java.awt.Color(0, 51, 204));
        bnt_salvar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bnt_salvar.setText("Inserir");
        bnt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_salvarActionPerformed(evt);
            }
        });

        bnt_excluir.setBackground(new java.awt.Color(204, 0, 51));
        bnt_excluir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        bnt_excluir.setText("Excluir");
        bnt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_excluirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "DESCRIÇÃO", "PRIORIDADE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bnt_mostrar.setText("dsd");
        bnt_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jL_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jL_descricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jL_prioridade))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tarefa)
                            .addComponent(txt_descricao)
                            .addComponent(cbx_nivel_prioridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bnt_salvar)
                                .addGap(18, 18, 18)
                                .addComponent(bnt_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                                .addComponent(bnt_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_titulo)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jL_descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jL_prioridade)
                .addGap(18, 18, 18)
                .addComponent(cbx_nivel_prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_salvar)
                    .addComponent(bnt_excluir)
                    .addComponent(bnt_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_excluirActionPerformed
       int selectedRow = jTable1.getSelectedRow();

if (selectedRow != -1) {
    try {
        // Supondo que o ID esteja na primeira coluna (índice 0)
        int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        TarefaDAO dao = new TarefaDAO();
        boolean excluiu = dao.excluir(id);

        if (excluiu) {
            JOptionPane.showMessageDialog(this, "Tarefa excluída com sucesso!");
            bnt_mostrarActionPerformed(null); // Recarrega a tabela
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a tarefa no banco.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao identificar a tarefa selecionada.");
    }
} else {
    JOptionPane.showMessageDialog(this, "Selecione uma tarefa para excluir.");
}
    }//GEN-LAST:event_bnt_excluirActionPerformed

    private void bnt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_salvarActionPerformed
        String titulo = txt_tarefa.getText();
        String descricao = txt_descricao.getText();
        String prioridade = cbx_nivel_prioridade.getSelectedItem().toString();

        if (!titulo.isEmpty() && !descricao.isEmpty()) {
            Tarefa tarefaObj = new Tarefa();
            tarefaObj.setTitulo(titulo);
            tarefaObj.setDescricao(descricao);
            tarefaObj.setPrioridade(prioridade);

            TarefaDAO dao = new TarefaDAO();
            boolean salvo = dao.inserir(tarefaObj);

            if (salvo) {
                JOptionPane.showMessageDialog(this, "Tarefa salva com sucesso!");
                bnt_mostrarActionPerformed(null); // Atualiza a lista mostrando todas com ID
                txt_tarefa.setText("");
                txt_descricao.setText("");
                cbx_nivel_prioridade.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar no banco de dados!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bnt_salvarActionPerformed

    private void bnt_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_mostrarActionPerformed
       TarefaDAO dao = new TarefaDAO();
    java.util.List<Tarefa> lista = dao.listar();

    // Modelo da tabela
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("TÍTULO");
    modelo.addColumn("DESCRIÇÃO");
    modelo.addColumn("PRIORIDADE");

    // Preenche o modelo com os dados
    for (Tarefa tarefa : lista) {
        modelo.addRow(new Object[]{
            tarefa.getId(),
            tarefa.getTitulo(),
            tarefa.getDescricao(),
            tarefa.getPrioridade()
        });
    }

    // Aplica o modelo na tabela
    jTable1.setModel(modelo);
    }//GEN-LAST:event_bnt_mostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarefaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarefaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarefaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarefaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TarefaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_excluir;
    private javax.swing.JButton bnt_mostrar;
    private javax.swing.JButton bnt_salvar;
    private javax.swing.JComboBox<String> cbx_nivel_prioridade;
    private javax.swing.JLabel jL_descricao;
    private javax.swing.JLabel jL_prioridade;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_tarefa;
    // End of variables declaration//GEN-END:variables

    
}
